blog2/article/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	users_list,
	user_article
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^users/$', users_list, name='users'),
	url(r'^users/(?P<pk>[0-9]+)/$', user_article, name='user_post'),
    url(r'^create/$', post_create),
    url(r'^(?P<pk>[0-9]+)/$', post_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', post_update, name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

blog2/blog2/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('article.urls', namespace='posts')),
]

blog2/article/models.py
from django.db import models

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone

from django.utils.text import slugify

# Create your models here.



class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-timestamp", "-updated"]

blog2/article/forms.py
from django import forms


from .models import Article


class PostForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            "title",
            "content",
            "draft",
        ]

blog2/article/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm
from .models import Article


@login_required
def post_create(request):
		
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

@login_required
def post_detail(request, pk=None):
	instance = get_object_or_404(Article, pk=pk)

	context = {
		"title": instance.title,
		"instance": instance,
	}
	return render(request, "post_detail.html", context)


@login_required
def post_list(request):
	queryset_list = Article.objects.all()
	
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset, 
		"title": "List",
		"page_request_var": page_request_var,
	}
	return render(request, "post_list.html", context)




@login_required
def post_update(request, pk=None):

	instance = get_object_or_404(Article, pk=pk)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "post_form.html", context)


@login_required
def post_delete(request, pk=None):

	instance = get_object_or_404(Article, pk=pk)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")


@login_required
def users_list(request):

	instance = User.objects.all()

	return render(request, "users_list.html", {"instance": instance})

@login_required
def user_article(request, pk=None):

	instance = Article.objects.filter(user=pk)

	return render(request, "user_article.html", {'instance': instance})

blog2/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %}The Blog{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >


<link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>
{% block style %}{% endblock style %}
</style>

</head>
<body>



{% include "messages_display.html" %}
<div class='container'> 

{% block content %}{% endblock content %}
</div>




<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>



</body>
</html>

blog2/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

blog2/templates/post_detail.html
{% extends "base.html" %}



{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


 {% block post_detail_link %}
  <li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
  {% endblock %}



{% block content %}
<div class='col-sm-6 col-sm-offset-3'>

<h1>{{ title }} <small>{% if instance.draft %}<span style='color:red;'>Draft</span> {% endif %}{{ instance.timestamp }}</small></h1>
<blockquote>{{ instance.content }}</blockquote>

<p>Author: {{ instance.user }}</p>

<hr/>
</p>

</div>


{% endblock content %}

blog2/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}



{% block content %}
<div class="row">

<h1>Form</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>

</div>
{% endblock content %}

blog2/templates/post_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>Articles list</h1>
    <h3><a href="{% url 'posts:users' %}">Users list</a></h3>
{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
      <div class="caption post-detail-item">
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
        <p>Author: {{ obj.user }}</p>
        {{ obj.content|truncatechars_html:120 }}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>




</div>

{% endblock content %}

blog2/templates/user_article.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
{% for instance in instance %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
      <div class="caption post-detail-item">
        <h3><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a> <small>{{ instance.publish }}</small></h3>
        <p>Author: {{ instance.user }}</p>
        {{ instance.content|truncatechars_html:120 }}
        <p><a href="{{ instance.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}




</div>

{% endblock content %}

blog2/templates/users_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>Users list</h1>
{% for instance in instance %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
      <div class="caption post-detail-item">
        <h3><a href="/blog/users/{{ instance.id }}/">{{ instance.username }}</a> </h3>
        <p>First name: {{ instance.first_name }}</p>
        <p>Last name: {{ instance.last_name }}</p>
        <p>Email: {{ instance.email }}<p>
        <p><a href="/blog/users/{{ instance.id }}/" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}




</div>

{% endblock content %}